export const themes = [
  {
    id: "princesse",
    name: "✨ Royaume de Princesse",
    age: "4-7 ans",
    desc: "Un univers magique et féérique où chaque enfant devient un prince ou une princesse.",
    emotionalDesc: "Conte de fées, magie douce, couronnes, robes, chasse au trésor magique, douceur.",
    kit: 19,
    energyLevel: "Créatif",
    duration: "2h",
    budgetIndicative: "150-400€",
    includes: [
      "Invitations royales à imprimer",
      "Décoration châ­teau à faire soi-même",
      "Jeux : chasse au trésor magique, danse de princesse",
      "Couronne à customiser",
      "Diplôme de prince/princesse",
    ],
    animations: ["Animation royale 1h30", "Atelier couronne", "Maquillage féerique"],
    decoration: "Château en carton, guirlandes roses et or, ballons pastel, tapis de trésor",
    games: "Chasse au trésor magique, danse de la reine, relais couronne, jeu du miroir magique",
  },
  {
    id: "superhero",
    name: "🦸 Mission Super-Héros",
    age: "5-9 ans",
    desc: "Devenez un super-héros et sauvez la ville lors de missions impossibles.",
    emotionalDesc: "Missions, défis épiques, badges de héros, sauvetage final, pouvoir spécial.",
    kit: 22,
    energyLevel: "Dynamique",
    duration: "2h30",
    budgetIndicative: "200-450€",
    includes: [
      "Invitations style BD",
      "Capes de héros à imprimer",
      "Missions secrètes à accomplir",
      "Badges de pouvoir",
      "Diplôme de super-héros",
      "Checklist des défis",
    ],
    animations: ["Animation super-héros 1h30", "Atelier création de cape", "Défis physiques"],
    decoration: "Banderoles explosions, graffitis BD, couleurs vives, éclairages dynamiques",
    games: "Missions secrètes, relais de pouvoir, chasse aux vilains, défi final de sauvetage",
  },
  {
    id: "pirate",
    name: "☠️ Chasse au Trésor Pirate",
    age: "5-8 ans",
    desc: "Embarquez pour une aventure sur les mers à la recherche du trésor caché.",
    emotionalDesc: "Carte au trésor, coffre, énigmes, aventure, esprit pirate, exploration.",
    kit: 24,
    energyLevel: "Aventure",
    duration: "2h",
    budgetIndicative: "180-380€",
    includes: [
      "Carte au trésor à imprimer",
      "Bandeau de pirate à customiser",
      "Énigmes et défis",
      "Certificat de pirate",
      "Jeux de pirates",
    ],
    animations: ["Animation pirate 1h30", "Atelier bandeau pirate", "Jeu du coffre"],
    decoration: "Drapeau pirate, filet de pêche, tonneaux, pièces d'or en carton, bateau",
    games: "Chasse au trésor avec énigmes, jeu du coffre, combat de pirates, relais du butin",
  },
  {
    id: "licorne",
    name: "🦄 Monde Licorne Arc-en-Ciel",
    age: "4-8 ans",
    desc: "Entrez dans un univers de couleurs pastel, de paillettes et de magie douce.",
    emotionalDesc: "Couleurs arc-en-ciel, paillettes, créativité, magie, douceur, rêve.",
    kit: 19,
    energyLevel: "Créatif",
    duration: "2h",
    budgetIndicative: "160-350€",
    includes: [
      "Invitations pastel",
      "Décoration arc-en-ciel",
      "Atelier slime pailleté",
      "Couronne licorne",
      "Jeux de magie",
    ],
    animations: ["Animation licorne 1h30", "Atelier créatif paillettes", "Maquillage licorne"],
    decoration: "Nuages en coton, paillettes partout, ballons pastel, arc-en-ciel",
    games: "Atelier slime, jeu du nuage, chasse à la potion magique, danse de la licorne",
  },
  {
    id: "minecraft",
    name: "🎮 Minecraft - Quête de Blocs",
    age: "7-10 ans",
    desc: "Construisez votre propre monde de cubes et accomplissez des quêtes épiques.",
    emotionalDesc: "Univers de cubes, défis par équipes, chasse aux ressources, création.",
    kit: 26,
    energyLevel: "Dynamique",
    duration: "2h30",
    budgetIndicative: "220-480€",
    includes: [
      "Invitations style Minecraft",
      "Cubes à construire",
      "Défis par équipes",
      "Chasse aux ressources",
      "Diplôme gamer",
    ],
    animations: ["Animation Minecraft 2h", "Tournoi de défis", "Atelier création"],
    decoration: "Cubes verts et marron, herbe de Minecraft, TNT en carton, torches",
    games: "Chasse aux ressources, construction de forteresse, combat PvP, quête finale",
  },
  {
    id: "football",
    name: "⚽ Mini-Tournoi de Football",
    age: "6-10 ans",
    desc: "Un vrai tournoi sportif avec équipes, défis et ambiance stade.",
    emotionalDesc: "Esprit d'équipe, compétition positive, fête, victoire, ambiance dynamique.",
    kit: 23,
    energyLevel: "Dynamique",
    duration: "2h",
    budgetIndicative: "170-350€",
    includes: [
      "Invitations style foot",
      "Gilets d'équipe",
      "Torneaux et défis",
      "Podium et trophées",
      "Diplôme joueur",
    ],
    animations: ["Animation foot 2h", "Tournoi encadré", "Ateliers skills"],
    decoration: "Drapeau équipes, ballons géants, mur des scores, podium",
    games: "Tournoi de football, défis techniques, relais dribling, match final",
  },
  {
    id: "science",
    name: "🔬 Labo du Petit Scientifique",
    age: "7-10 ans",
    desc: "Expériences simples mais spectaculaires pour les budding scientists.",
    emotionalDesc: "Expériences wow, lunettes de scientifique, découverte, curiosité.",
    kit: 29,
    energyLevel: "Créatif",
    duration: "2h",
    budgetIndicative: "210-420€",
    includes: [
      "Invitations scientifiques",
      "Lunettes de labo",
      "Recettes d'expériences",
      "Kit de réactions chimiques",
      "Diplôme scientifique",
    ],
    animations: ["Animation scientifique 1h30", "Ateliers réactions", "Démonstrations wow"],
    decoration: "Béchers géants, liquides colorés, tubes, éprouvettes, ambiance labo",
    games: "Expériences guidées, défi alchimiste, potion magique, explosion volcanique",
  },
  {
    id: "jungle",
    name: "🦁 Safari Jungle Aventure",
    age: "4-8 ans",
    desc: "Explorez la jungle et rencontrez les animaux sauvages en mission secrète.",
    emotionalDesc: "Animaux, exploration, aventure, découverte, sensibilité à la nature.",
    kit: 23,
    energyLevel: "Aventure",
    duration: "2h",
    budgetIndicative: "180-380€",
    includes: [
      "Invitations jungle",
      "Masques d'animaux",
      "Mission de explorer",
      "Safari bingo",
      "Diplôme explorateur",
    ],
    animations: ["Animation jungle 1h30", "Atelier masques animaux", "Safari jeu"],
    decoration: "Lianes en carton, feuillage, animaux en peluche/affiche, ambiance verte",
    games: "Chasse aux animaux, défi explorateur, safari bingo, danse des animaux",
  },
  {
    id: "dinosaure",
    name: "🦕 Fouilles Dinosaures Jurassic",
    age: "4-7 ans",
    desc: "Devenez paléontologue et découvrez des fossiles dans le désert de la préhistoire.",
    emotionalDesc: "Fouilles, œufs de dinosaures, aventure préhistorique, découverte.",
    kit: 19,
    energyLevel: "Aventure",
    duration: "2h",
    budgetIndicative: "160-360€",
    includes: [
      "Invitations dinosaure",
      "Œufs à creuser (cachés)",
      "Diplôme paléontologue",
      "Fossiles à imprimer",
      "Jeux de fouilles",
    ],
    animations: ["Animation dinosaure 1h30", "Atelier fouilles", "Chasse aux œufs"],
    decoration: "Volcans en carton, fossiles, sable, rochers, ambiance préhistorique",
    games: "Fouilles de fossiles, chasse aux œufs, défi volcan, danse dinosaure",
  },
  {
    id: "spa",
    name: "💅 Spa Kids Girly Party",
    age: "8-11 ans",
    desc: "Détente, beauté et atmosphère pyjama party avec ateliers well-being.",
    emotionalDesc: "Détente, beauté douce, bracelets, mini-soins, ambiance chill, amies.",
    kit: 25,
    energyLevel: "Calme",
    duration: "2h",
    budgetIndicative: "190-380€",
    includes: [
      "Invitations spa",
      "Masques DIY",
      "Kits bracelets",
      "Vernis paillettes",
      "Diplôme spa girl",
    ],
    animations: ["Animatrice spa 2h", "Ateliers bien-être", "Maquillage"],
    decoration: "Bougies, fleurs, ambiance zen, coussins, tissu doux, couleurs relaxantes",
    games: "Atelier masque, création bracelets, manucure pailletée, jeu des confidences",
  },
  {
    id: "atelier",
    name: "🎨 Atelier Créatif Hands-On",
    age: "5-10 ans",
    desc: "Créez, peignez, customisez vos propres œuvres à ramener chez vous.",
    emotionalDesc: "Créativité, fierté, à emporter, diversité d'ateliers possibles.",
    kit: 27,
    energyLevel: "Créatif",
    duration: "2h30",
    budgetIndicative: "210-420€",
    includes: [
      "Invitations créatives",
      "Matériel peinture/dessin",
      "Toiles ou supports",
      "Vernis pailletés",
      "Boîtes cadeaux pour ramener",
    ],
    animations: ["Animateur créatif 2h", "Ateliers au choix", "Exposition finale"],
    decoration: "Chevalet, palettes géantes, toiles, art partout, couleurs vives",
    games: "Atelier peinture, customisation, dessin collectif, exposition galerie",
  },
  {
    id: "escape",
    name: "🔐 Escape Game Enfant Énigmes",
    age: "8-12 ans",
    desc: "Travaillez en équipe pour résoudre énigmes et sortir de la pièce secrète.",
    emotionalDesc: "Énigmes, mission secrète, équipe, chronomètre, défi intellectuel.",
    kit: 31,
    energyLevel: "Dynamique",
    duration: "2h",
    budgetIndicative: "240-500€",
    includes: [
      "Invitations mission",
      "Énigmes adaptées",
      "Clés cachées",
      "Diplôme escape agent",
      "Indices progressifs",
    ],
    animations: ["Escape game 1h30", "Débriefing", "Remise de diplôme"],
    decoration: "Mystérieux, clés, codes cachés, coffre, ambiance secrète, indices",
    games: "Escape game complet, résolution d'énigmes, chasse aux clés, défi final",
  },
];

export const providers = [
  {
    name: "Sarah Animation",
    type: "Animatrice tous thèmes",
    city: "Amiens",
    rating: 4.9,
    price: 120,
    tags: ["Thèmes", "Tous âges", "Dynamique"],
    expertise: "Spécialisée dans les animations à thème pour tous les âges",
  },
  {
    name: "Gâteaux & Gourmandises",
    type: "Pâtissière spécialisée",
    city: "Amiens",
    rating: 4.8,
    price: 45,
    tags: ["Gâteau", "Personnalisé", "Vegan disponible"],
    expertise: "Gâteaux personnalisés adaptés au thème, sans gluten sur demande",
  },
  {
    name: "Décor & Ballons Magic",
    type: "Décoratrice événements",
    city: "Amiens",
    rating: 4.7,
    price: 80,
    tags: ["Décoration", "Ballons", "Thème"],
    expertise: "Transformation complète des espaces avec décor thématique",
  },
  {
    name: "Claire Photo Studio",
    type: "Photographe spécialisée enfants",
    city: "Amiens",
    rating: 4.9,
    price: 150,
    tags: ["Photo", "Album numérique", "Souvenirs"],
    expertise: "Photographies professionnelles + album numérique livré 48h",
  },
  {
    name: "Jeux & Activités Fun",
    type: "Animateur de loisirs",
    city: "Amiens Métropole",
    rating: 4.6,
    price: 90,
    tags: ["Jeux", "Animation", "Enfants"],
    expertise: "Jeux collectifs, défis, animations sans matériel compliqué",
  },
  {
    name: "Maquillage Artistique Emma",
    type: "Maquilleuse créative",
    city: "Amiens",
    rating: 4.8,
    price: 60,
    tags: ["Maquillage", "Art", "Créatif"],
    expertise: "Maquillage artistique : animaux, héros, designs fantastiques",
  },
  {
    name: "Location Fête Matériel",
    type: "Location d'équipements",
    city: "Amiens",
    rating: 4.5,
    price: 50,
    tags: ["Location", "Tables", "Tapis rebond"],
    expertise: "Tables, chaises, tapis rebond, jeux gonflables disponibles",
  },
  {
    name: "Aide Installation & Rangement",
    type: "Coup de main invisible",
    city: "Amiens",
    rating: 4.7,
    price: 40,
    tags: ["Installation", "Rangement", "Discrétion"],
    expertise: "Mise en place le jour J + rangement/nettoyage après fête",
  },
];

export const faqItems = [
  {
    question: "MiniFête est-il disponible partout en France ?",
    answer: "Non, MiniFête se lance progressivement. Pour le moment, nous opérons à Amiens et ses alentours (Amiens Métropole, Longueau, Camon, Rivery, etc.). Nous étendons progressivement notre réseau local pour garantir des prestataires vérifiés et disponibles. Vous pouvez nous contacter pour savoir si votre ville est couverte.",
  },
  {
    question: "MiniFête garde-t-il les enfants ?",
    answer: "Non. MiniFête n'est pas un service de garde d'enfants. Un parent ou un adulte responsable DOIT rester présent pendant toute la durée de l'anniversaire. MiniFête vous aide à organiser et trouver des prestataires, mais la supervision de l'enfant vous incombe.",
  },
  {
    question: "Comment fonctionnel l'agent IA MiniFête ?",
    answer: "Répondez à 5 questions : âge de l'enfant, nombre d'invités, budget, thème, lieu et type d'aide. L'agent IA propose une formule complète et personnalisée : budget détaillé, prestations adaptées, déroulé horaire et précautions de sécurité.",
  },
  {
    question: "Peut-on respecter un petit budget ?",
    answer: "Oui ! L'agent IA propose une formule adaptée au budget indiqué et ne dépasse jamais ce montant. À partir de 19€ (kit digital), vous pouvez organiser un anniversaire mémorable.",
  },
  {
    question: "Puis-je choisir seulement un thème ou un kit ?",
    answer: "Bien sûr ! Vous pouvez acheter simplement un kit digital (invitations, jeux, décoration à imprimer) et tout faire vous-même. Vous pouvez aussi combiner : kit + une seule prestation comme l'animation ou le gâteau.",
  },
  {
    question: "Puis-je réserver seulement une animation ou un gâteau ?",
    answer: "Oui ! Allez sur la page Prestataires et contactez directement le professionnel qui vous intéresse. MiniFête est une plateforme de mise en relation, vous êtes libres de choisir les services individuels.",
  },
  {
    question: "Les prestataires de MiniFête sont-ils vérifiés ?",
    answer: "Oui. Tous les prestataires du réseau MiniFête sont progressivement vérifiés : références, assurance responsabilité civile, engagement envers la sécurité des enfants. La sécurité est notre priorité absolue.",
  },
  {
    question: "Y a-t-il des frais cachés de MiniFête ?",
    answer: "Non. MiniFête est une plateforme gratuite de mise en relation. Vous payez uniquement les prestataires pour les services que vous réservez. Il n'y a pas de commission MiniFête sur les transactions.",
  },
  {
    question: "Que faire en cas de problème avec un prestataire ?",
    answer: "Contactez-nous immédiatement via le formulaire de contact. Nous investiguerons et prendrons les mesures appropriées : remboursement, remise en relation avec un autre prestataire, ou autre solution.",
  },
  {
    question: "Puis-je modifier ma réservation après génération de la proposition ?",
    answer: "Oui ! La proposition de l'agent IA est un point de départ. Contactez directement les prestataires recommandés pour ajuster les détails, les délais, le budget ou les services.",
  },
  {
    question: "Comment devenir prestataire MiniFête ?",
    answer: "Allez sur la page 'Devenir prestataire' et remplissez le formulaire. Nous examinerons votre candidature, vérifierons vos références et votre assurance. Une fois approuvé(e), vous rejoindrez le réseau MiniFête.",
  },
  {
    question: "Quels sont les tarifs moyens d'un anniversaire avec MiniFête ?",
    answer: "Cela dépend entièrement de vos choix : kit digital (19€), animation (dès 89€), gâteau (dès 45€), décoration (dès 65€), aide (dès 35€). L'agent IA propose une formule adaptée à votre budget spécifique.",
  },
];
